# Generated by Django 3.2.7 on 2021-09-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
