# Generated by Django 3.2.8 on 2021-10-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_activity', '0003_remove_albumactivity_unique_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumactivity',
            name='activity',
            field=models.CharField(choices=[('WTL', 'want to listen')], max_length=3),
        ),
    ]
