version: "3.7"

services:
  nginx:
    build: ./nginx
    container_name: test_deploy_name
    ports:
      - "5000:80"
    volumes:
      - staticfiles:/app/static/
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app/
      - staticfiles:/app/static/
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hello

volumes:
  postgres_data:
  staticfiles:
