# Generated by Django 3.2.7 on 2021-09-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_alter_rating_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('-updated_at',)},
        ),
    ]
