# Generated by Django 3.2.8 on 2021-10-05 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210918_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(max_length=255)),
                ('activity', models.CharField(blank=True, choices=[('WTL', 'Want To Listen')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
