# Generated by Django 3.2.7 on 2021-09-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rename_comments_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, max_length=350),
        ),
    ]
